networks:
  internal:
volumes:
    pgdata:
services:
  postgres:
    image: postgres:15.8-alpine3.20
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: ticket_hub_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
        - internal
    volumes:
      - pgdata:/ticket-hub/postgres/data
#  app:
#    container_name: node_app
#    build:
#      context: .
#    volumes:
#      - .:/app
#      - /node_modules
#    ports:
#      - 3000:3000
#    environment:
#      DB_HOST: postgres
#    command: npm run start:dev
#    env_file:
#      - .env
#    networks:
#      - internal
#    depends_on:
#      - postgres